# scripts/11_configure_slurmdbd.sh
#!/usr/bin/env bash
set -euo pipefail

CLUSTER_NAME="${CLUSTER_NAME:-local}"

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-3306}"
DB_NAME="${DB_NAME:-slurm_acct_db}"
DB_USER="${DB_USER:-slurm}"
DB_PASS="${DB_PASS:-slurmpass_change_me}"

DBD_ADDR="${DBD_ADDR:-127.0.0.1}"
DBD_PORT="${DBD_PORT:-6819}"

SLURM_CONF="${SLURM_CONF:-/etc/slurm/slurm.conf}"
SLURMDBD_CONF="${SLURMDBD_CONF:-/etc/slurm/slurmdbd.conf}"

# If set to 1, enforce associations
ACCOUNTING_ENFORCE_ASSOC="${ACCOUNTING_ENFORCE_ASSOC:-0}"

HOST_SHORT="$(hostname -s)"

log() { echo -e "\n=== $* ==="; }

wait_tcp4() {
  local host="$1" port="$2" tries="${3:-60}" sleep_s="${4:-1}"
  for _ in $(seq 1 "$tries"); do
    if nc -4 -vz "$host" "$port" >/dev/null 2>&1; then
      return 0
    fi
    sleep "$sleep_s"
  done
  return 1
}

log "Step 11: Configure slurmdbd (systemd-hardened) + enable accounting"
echo "CLUSTER_NAME=${CLUSTER_NAME}"
echo "DB=${DB_HOST}:${DB_PORT}  DB_NAME=${DB_NAME}  DB_USER=${DB_USER}"
echo "DBD_ADDR=${DBD_ADDR}  DBD_PORT=${DBD_PORT}"
echo "SLURM_CONF=${SLURM_CONF}"
echo "SLURMDBD_CONF=${SLURMDBD_CONF}"

log "[1/10] Install slurmdbd + mariadb-client + nc"
sudo apt-get update -y
sudo apt-get install -y slurmdbd mariadb-client netcat-openbsd

log "[2/10] Ensure munge is enabled+running"
sudo systemctl enable --now munge
sudo systemctl restart munge

log "[3/10] Ensure /run/slurm is created on boot (tmpfiles)"
sudo tee /etc/tmpfiles.d/slurm.conf >/dev/null <<'EOF'
d /run/slurm 0755 slurm slurm -
EOF
sudo systemd-tmpfiles --create

log "[4/10] Create runtime/log dirs now (correct perms)"
sudo mkdir -p /run/slurm /var/log/slurm
sudo chown slurm:slurm /run/slurm /var/log/slurm
sudo chmod 0755 /run/slurm /var/log/slurm

log "[5/10] Write slurmdbd.conf (0600, owned by slurm)"
sudo mkdir -p /etc/slurm
sudo tee "${SLURMDBD_CONF}" >/dev/null <<EOF
# Auto-generated by scripts/11_configure_slurmdbd.sh
AuthType=auth/munge

# Identity MUST match controller's host naming (use short hostname)
DbdHost=${HOST_SHORT}

# Listen only on IPv4 loopback to avoid ::1 surprises
DbdAddr=${DBD_ADDR}
DbdPort=${DBD_PORT}

SlurmUser=slurm

StorageType=accounting_storage/mysql
StorageHost=${DB_HOST}
StoragePort=${DB_PORT}
StorageUser=${DB_USER}
StoragePass=${DB_PASS}
StorageLoc=${DB_NAME}

LogFile=/var/log/slurm/slurmdbd.log
PidFile=/run/slurm/slurmdbd.pid
EOF
sudo chown slurm:slurm "${SLURMDBD_CONF}"
sudo chmod 0600 "${SLURMDBD_CONF}"

log "[6/10] Install systemd override for slurmdbd (RuntimeDirectory + DB wait + restart policy)"
sudo mkdir -p /etc/systemd/system/slurmdbd.service.d
sudo tee /etc/systemd/system/slurmdbd.service.d/override.conf >/dev/null <<EOF
[Service]
RuntimeDirectory=slurm
RuntimeDirectoryMode=0755
ExecStartPre=/usr/bin/install -d -m 0755 -o slurm -g slurm /run/slurm
ExecStartPre=/bin/sh -c 'for i in \$(seq 1 30); do nc -4 -z ${DB_HOST} ${DB_PORT} && exit 0; sleep 1; done; exit 1'
Restart=on-failure
RestartSec=2
EOF

sudo systemctl daemon-reload

log "[7/10] Start/restart slurmdbd and wait until it REALLY listens"
sudo systemctl enable --now slurmdbd
sudo systemctl restart slurmdbd

if ! wait_tcp4 "${DBD_ADDR}" "${DBD_PORT}" 60 1; then
  echo "ERROR: slurmdbd not reachable on ${DBD_ADDR}:${DBD_PORT}"
  sudo systemctl status slurmdbd --no-pager || true
  sudo journalctl -u slurmdbd -n 200 --no-pager || true
  sudo tail -n 200 /var/log/slurm/slurmdbd.log 2>/dev/null || true
  exit 1
fi

log "[8/10] Patch slurm.conf to use slurmdbd + cgroups (idempotent)"
sudo test -f "${SLURM_CONF}" || { echo "ERROR: Missing ${SLURM_CONF}. Run init_local.sh first."; exit 1; }

sudo sed -i \
  -e '/^AccountingStorageType=/d' \
  -e '/^AccountingStorageHost=/d' \
  -e '/^AccountingStoragePort=/d' \
  -e '/^AccountingStorageEnforce=/d' \
  -e '/^JobAcctGatherType=/d' \
  -e '/^ProctrackType=/d' \
  -e '/^TaskPlugin=/d' \
  -e '/^MpiDefault=/d' \
  "${SLURM_CONF}"

sudo tee -a "${SLURM_CONF}" >/dev/null <<EOF

# --- accounting via slurmdbd (Step 11) ---
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=${DBD_ADDR}
AccountingStoragePort=${DBD_PORT}
EOF

if [[ "${ACCOUNTING_ENFORCE_ASSOC}" == "1" ]]; then
  sudo tee -a "${SLURM_CONF}" >/dev/null <<'EOF'
AccountingStorageEnforce=associations
EOF
fi

sudo tee -a "${SLURM_CONF}" >/dev/null <<'EOF'
ProctrackType=proctrack/cgroup
TaskPlugin=task/cgroup
JobAcctGatherType=jobacct_gather/cgroup

# Avoid PMIx plugin noise
MpiDefault=none
EOF

log "[9/10] Restart slurmctld/slurmd"
sudo systemctl restart slurmctld slurmd

log "[10/10] Ensure cluster '${CLUSTER_NAME}' exists in accounting DB"
if sudo sacctmgr -n -P show cluster format=Cluster | cut -d'|' -f1 | grep -qx "${CLUSTER_NAME}"; then
  echo "Cluster '${CLUSTER_NAME}' already registered."
else
  sudo sacctmgr -i add cluster "${CLUSTER_NAME}"
fi

echo
echo "OK: Step 11 complete."
echo "Verify:"
echo "  nc -4 -vz ${DBD_ADDR} ${DBD_PORT}"
echo "  scontrol show config | egrep -i 'AccountingStorageType|AccountingStorageHost|AccountingStoragePort|JobAcctGatherType'"
