#!/usr/bin/env bash
set -euo pipefail

CLUSTER_NAME="${CLUSTER_NAME:-local}"

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-3306}"
DB_NAME="${DB_NAME:-slurm_acct_db}"
DB_USER="${DB_USER:-slurm}"
DB_PASS="${DB_PASS:-slurmpass_change_me}"

# slurmdbd listens here; slurmctld/sacctmgr must match
DBD_PORT="${DBD_PORT:-6819}"

SLURM_CONF="${SLURM_CONF:-/etc/slurm/slurm.conf}"
SLURMDBD_CONF="${SLURMDBD_CONF:-/etc/slurm/slurmdbd.conf}"

echo "=== Step 11: Configure slurmdbd + enable accounting (provider mode) ==="
echo "CLUSTER_NAME=${CLUSTER_NAME}"
echo "DB_HOST=${DB_HOST}:${DB_PORT}  DB_NAME=${DB_NAME}  DB_USER=${DB_USER}"
echo "DBD_PORT=${DBD_PORT}"
echo "SLURM_CONF=${SLURM_CONF}"
echo "SLURMDBD_CONF=${SLURMDBD_CONF}"
echo "======================================================================="

echo "[1/8] Install slurmdbd + mariadb-client..."
sudo apt-get update
sudo apt-get install -y slurmdbd mariadb-client

echo "[2/8] Ensure munge is running..."
sudo systemctl enable --now munge

echo "[3/8] Write slurmdbd.conf (600 perms)..."
sudo tee "${SLURMDBD_CONF}" >/dev/null <<EOF
# Auto-generated by scripts/11_configure_slurmdbd.sh
AuthType=auth/munge
DbdHost=localhost
DbdPort=${DBD_PORT}
SlurmUser=slurm

StorageType=accounting_storage/mysql
StorageHost=${DB_HOST}
StoragePort=${DB_PORT}
StorageUser=${DB_USER}
StoragePass=${DB_PASS}
StorageLoc=${DB_NAME}

LogFile=/var/log/slurmdbd.log
PidFile=/run/slurmdbd.pid
EOF

sudo chown slurm:slurm "${SLURMDBD_CONF}"
sudo chmod 600 "${SLURMDBD_CONF}"

echo "[4/8] Start/restart slurmdbd..."
sudo systemctl enable --now slurmdbd
sudo systemctl restart slurmdbd

echo "[5/8] Patch slurm.conf to use slurmdbd + cgroups (idempotent)..."
# Remove keys we manage to avoid duplicates
sudo sed -i \
  -e '/^AccountingStorageType=/d' \
  -e '/^AccountingStorageHost=/d' \
  -e '/^AccountingStoragePort=/d' \
  -e '/^JobAcctGatherType=/d' \
  -e '/^ProctrackType=/d' \
  -e '/^TaskPlugin=/d' \
  -e '/^MpiDefault=/d' \
  "${SLURM_CONF}"

sudo tee -a "${SLURM_CONF}" >/dev/null <<EOF

# --- provider-style accounting + enforcement (Step 11) ---
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=localhost
AccountingStoragePort=${DBD_PORT}

ProctrackType=proctrack/cgroup
TaskPlugin=task/cgroup
JobAcctGatherType=jobacct_gather/cgroup

# Avoid PMIx plugin noise
MpiDefault=none
EOF

echo "[6/8] Restart slurmctld/slurmd..."
sudo systemctl restart slurmctld slurmd

echo "[7/8] Verify slurmdbd is listening on ${DBD_PORT}..."
# ss is usually available; netstat fallback
if command -v ss >/dev/null 2>&1; then
  sudo ss -lntp | grep -E ":${DBD_PORT}\b" || {
    echo "ERROR: slurmdbd not listening on port ${DBD_PORT}."
    echo "slurmdbd status:"
    sudo systemctl status slurmdbd --no-pager | head -n 60 || true
    echo "slurmdbd log tail:"
    sudo tail -n 120 /var/log/slurmdbd.log || true
    exit 1
  }
else
  sudo netstat -lntp 2>/dev/null | grep -E ":${DBD_PORT}\b" || true
fi

echo "[8/8] Register cluster '${CLUSTER_NAME}' in accounting (creates per-cluster tables)..."
# sacctmgr uses slurmdbd; if it fails, show targeted debugging info
if ! sudo sacctmgr -i add cluster "${CLUSTER_NAME}"; then
  echo
  echo "ERROR: sacctmgr could not connect/register cluster."
  echo "Check slurmdbd status + logs:"
  sudo systemctl status slurmdbd --no-pager | head -n 80 || true
  sudo tail -n 200 /var/log/slurmdbd.log || true
  exit 1
fi

echo
echo "OK: Step 11 complete."
echo "Verify:"
echo "  sudo sacctmgr show cluster"
echo "  scontrol show config | grep -E 'AccountingStorageType|AccountingStorageHost|AccountingStoragePort|JobAcctGatherType|ProctrackType|TaskPlugin|MpiDefault'"
echo "Next step: scripts/12_create_accounts_users.sh"
