#!/usr/bin/env bash
set -euo pipefail

CLUSTER_NAME="${CLUSTER_NAME:-local}"

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-3306}"
DB_NAME="${DB_NAME:-slurm_acct_db}"
DB_USER="${DB_USER:-slurm}"
DB_PASS="${DB_PASS:-slurmpass_change_me}"

# slurmdbd listens here; slurmctld/sacctmgr must match
DBD_PORT="${DBD_PORT:-6819}"

SLURM_CONF="${SLURM_CONF:-/etc/slurm/slurm.conf}"
SLURMDBD_CONF="${SLURMDBD_CONF:-/etc/slurm/slurmdbd.conf}"

echo "=== Step 11: Configure slurmdbd + enable accounting ==="
echo "CLUSTER_NAME=${CLUSTER_NAME}"
echo "DB=${DB_HOST}:${DB_PORT}  DB_NAME=${DB_NAME}  DB_USER=${DB_USER}"
echo "DBD_PORT=${DBD_PORT}"
echo "SLURM_CONF=${SLURM_CONF}"
echo "SLURMDBD_CONF=${SLURMDBD_CONF}"
echo "======================================================"

echo "[1/9] Install slurmdbd + mariadb-client..."
sudo apt-get update
sudo apt-get install -y slurmdbd mariadb-client

echo "[2/9] Ensure munge is running..."
sudo systemctl enable --now munge

echo "[3/9] Ensure slurm log/run dirs exist..."
sudo mkdir -p /var/log/slurm /run/slurm
sudo chown slurm:slurm /var/log/slurm /run/slurm
sudo chmod 755 /var/log/slurm /run/slurm

echo "[4/9] Write slurmdbd.conf (600 perms)..."
sudo tee "${SLURMDBD_CONF}" >/dev/null <<EOF
# Auto-generated by scripts/11_configure_slurmdbd.sh
AuthType=auth/munge
DbdHost=localhost
DbdPort=${DBD_PORT}
SlurmUser=slurm

StorageType=accounting_storage/mysql
StorageHost=${DB_HOST}
StoragePort=${DB_PORT}
StorageUser=${DB_USER}
StoragePass=${DB_PASS}
StorageLoc=${DB_NAME}

LogFile=/var/log/slurm/slurmdbd.log
PidFile=/run/slurm/slurmdbd.pid
EOF

sudo chown slurm:slurm "${SLURMDBD_CONF}"
sudo chmod 600 "${SLURMDBD_CONF}"

echo "[5/9] Start/restart slurmdbd..."
sudo systemctl enable --now slurmdbd
sudo systemctl restart slurmdbd

echo "[6/9] Wait for slurmdbd to listen on ${DBD_PORT}..."
for i in $(seq 1 40); do
  if command -v ss >/dev/null 2>&1; then
    if sudo ss -lntp | grep -qE ":${DBD_PORT}\b"; then
      break
    fi
  else
    if sudo netstat -lntp 2>/dev/null | grep -qE ":${DBD_PORT}\b"; then
      break
    fi
  fi

  if [[ "${i}" -eq 40 ]]; then
    echo "ERROR: slurmdbd not listening on ${DBD_PORT}."
    sudo systemctl status slurmdbd --no-pager | head -n 120 || true
    sudo tail -n 200 /var/log/slurm/slurmdbd.log || true
    exit 1
  fi
  sleep 1
done

echo "[7/9] Patch slurm.conf to use slurmdbd + cgroups (idempotent)..."
# Remove keys we manage to avoid duplicates
sudo sed -i \
  -e '/^AccountingStorageType=/d' \
  -e '/^AccountingStorageHost=/d' \
  -e '/^AccountingStoragePort=/d' \
  -e '/^JobAcctGatherType=/d' \
  -e '/^ProctrackType=/d' \
  -e '/^TaskPlugin=/d' \
  -e '/^MpiDefault=/d' \
  "${SLURM_CONF}"

sudo tee -a "${SLURM_CONF}" >/dev/null <<EOF

# --- provider-style accounting + enforcement (Step 11) ---
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=localhost
AccountingStoragePort=${DBD_PORT}

ProctrackType=proctrack/cgroup
TaskPlugin=task/cgroup
JobAcctGatherType=jobacct_gather/cgroup

# Avoid PMIx plugin noise
MpiDefault=none
EOF

echo "[8/9] Restart slurmctld/slurmd..."
sudo systemctl restart slurmctld slurmd

echo "[9/9] Register or update cluster '${CLUSTER_NAME}' in accounting..."
HN="$(hostname -s)"

if sudo sacctmgr show cluster -n -P format=Cluster | cut -d'|' -f1 | grep -qx "${CLUSTER_NAME}"; then
  echo "Cluster exists — updating ControlHost/ControlPort."
  sudo sacctmgr -i modify cluster where Cluster="${CLUSTER_NAME}" \
    set ControlHost="${HN}" ControlPort=6817
else
  echo "Registering new cluster."
  sudo sacctmgr -i add cluster "${CLUSTER_NAME}"
  sudo sacctmgr -i modify cluster where Cluster="${CLUSTER_NAME}" \
    set ControlHost="${HN}" ControlPort=6817
fi

echo
echo "OK: Step 11 complete."
echo "Verify:"
echo "  sudo sacctmgr show cluster"
echo "  scontrol show config | grep -E 'AccountingStorageType|AccountingStorageHost|AccountingStoragePort|JobAcctGatherType|ProctrackType|TaskPlugin|MpiDefault'"
echo "Next step: scripts/12_create_accounts_users.sh"
